name: Maven Publish Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Packages Maven Default
      run: mvn deploy -s .github/workflows/settings.xml -DaltDeploymentRepository=gitlab::default::$GITLAB_URL
      env:
        GITLAB_URL: https://gitlab.com/api/v4/projects/23719062/packages/maven
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        
    - name: Publish to Packages Maven Custom GroupId
      run: |
         export FILE=`ls target/*.jar`
         mvn deploy:deploy-file -s .github/workflows/settings.xml -DpomFile=pom.xml -Dfile=$FILE -DgroupId=$GITLAB_GROUPID \
            -Durl=$GITLAB_URL
      env:
        GITLAB_GROUPID: com.github.naskarlab
        GITLAB_URL: https://gitlab.com/api/v4/projects/23719062/packages/maven
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
